'''
Constants for resources and configurations.
'''
ELASTIC_DOMAIN  = 'search-code-snippets-x7pez2uta5ofjf4sch7o63dd2y'
ELASTIC_REGION  = 'us-east-2.es.amazonaws.com'
ELASTIC_SEARCH  = f'https://{ELASTIC_DOMAIN}.{ELASTIC_REGION}/'
AWS_REGION      = 'us-east-2'
SNIPPET_TABLE   = 'snippets'
DB              = 'dynamodb'
FILE_SYSTEM     = 's3'
ES_SERVICE      = 'es'
BUCKET          = 'snippets-s'
NAME            = 'nexus'
S3              = 'https://snippets-s.s3.us-east-2.amazonaws.com/'
