name: Branch Build & Deployment
on:
  push:
    branches:
      - '40-cicd-nm3223'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fetching Repository - ${{ github.ref }}"
      - uses: actions/checkout@v2
      - name: Initialize Branch Build
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Lint Project
        run: |
          echo "Starting a branch lint on ${{ github.ref }} for ${{ github.repository }}"
          python src/utilities/lint.py --path ./src --threshold 8.0
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Attempting to run test cases under test module"
      - uses: actions/checkout@v2
      - name: Run Test Cases
        env:
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.REGION }}
          KEYS_URL: ${{ secrets.KEYS_URL }}
        run: |
          echo "Running all test cases under test.* modules"
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
          python -m unittest discover
          coverage run -m unittest discover
          coverage html --omit="**/Library/*,*__init__.py" -d test/coverage
          echo "Publishing Results to S3"
          python src/utilities/coverage_delivery.py
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: "Attempting to build a docker image"
      - uses: actions/checkout@v2
      - name: Assemble and Deploy
        run: |
          echo "Starting a docker build on ${{ github.ref }} for ${{ github.repository }}"
          docker build -t nexus:${{ github.ref }}
          echo "Build successful"

